DIY.Castle/DIY.Castle.Web/Areas/Administration/Controllers/ProductsController.cs
using AutoMapper;
using DIY.Castle.Data.Models;
using DIY.Castle.Web.Areas.Administration.Models;
using DIY.Castle.Web.Models;
using DIY.Castle.Web.Services.CategoriesService;
using DIY.Castle.Web.Services.ProductsService;
using DIY.Castle.Web.Services.SubcategoriesService;
using DIY.Castle.Web.Services.UploadFileService;
using GlobalConstants;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DIY.Castle.Web.Areas.Administration.Controllers
{
    public class ProductsController : AdministrationController
    {
        private readonly IMapper _mapper;
        private readonly IUploadFileService _uploadFileService;
        private readonly IProductsService _productsService;
        private readonly ICategoriesService _categoriesService;
        private readonly ISubcategoriesService _subCategoriesService;

        public ProductsController(IMapper mapper, IUploadFileService uploadFileService, IProductsService productsService, ICategoriesService categoriesService, ISubcategoriesService subCategoriesService)
        {
            this._mapper = mapper;
            this._uploadFileService = uploadFileService;
            this._productsService = productsService;
            this._categoriesService = categoriesService;
            this._subCategoriesService = subCategoriesService;
        }

        [HttpGet]
        public IActionResult Create()
        {
            var categories = _categoriesService.GetAllCategories().ToList();
            var subcategories = _subCategoriesService.GetAllCategories().ToList();
            var model = new CreateProductModel() { Categories = categories, Subcategories = subcategories };
            return this.View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateProductModel model)
        {
            if (!this.ModelState.IsValid)
            {
                model.Categories = _categoriesService.GetAllCategories().ToList();
                model.Subcategories = _subCategoriesService.GetAllCategories().ToList();
                return this.View(model);
            }

            var variation = this._mapper.Map<CreateProductModel, Variation>(model);
            var product = this._mapper.Map<CreateProductModel, Product>(model);

            var productImgSourcePaths = string.Empty;

            var imgIndex = 0;
            foreach (var img in model.Images)
            {
                var imgSeparator = imgIndex != 0 ? CommonConstants.ImageSeparator : string.Empty;
                productImgSourcePaths += (imgSeparator + this._uploadFileService.UploadFile(img));

                imgIndex++;
            }

            product.Category = this._categoriesService.GetCategoryByName(model.Category);
            product.Subcategory = this._subCategoriesService.GetCategoryByName(model.Subcategory);
            product.ImageSourcePath = productImgSourcePaths;
            await this._productsService.AddProductAsync(product, variation);

            return this.RedirectToAction("Index", "Home", new { area = "" });
        }

        [HttpGet]
        public IActionResult Edit(int productId)
        {
            var allCategories = this._categoriesService.GetAllCategories().ToList();
            var allSubcategories = _subCategoriesService.GetAllCategories().ToList();
            var product = this._productsService.GetProductById(productId);

            var vm = new EditProductModel(product.Name, product.Description, product.Category.Name, allCategories, product.Subcategory.Name, allSubcategories);
            vm.ProductId = product.Id;

            return this.View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditProductModel model)
        {
            if (!this.ModelState.IsValid)
            {
                model.AllCategories = _categoriesService.GetAllCategories().ToList();
                model.AllSubcategories = _subCategoriesService.GetAllCategories().ToList();
                return this.View(model);
            }

            await this._productsService.UpdateProductAsync(model);

            return this.RedirectToAction("Product", "ProductDetails", new { area = "", id = model.ProductId });
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int productId)
        {
            // Deletes the product and his variations
            await this._productsService.DeleteProductAsync(productId);

            return this.RedirectToAction("Index", "Home", new { area = "" });
        }

        //[HttpPost]
        //public async Task<IActionResult> AddVariation(int productId)
        //{
            
        //}
    }
}

DIY.Castle/DIY.Castle.Web/Controllers/CatalogController.cs
using DIY.Castle.Common;
using DIY.Castle.Data.Models;
using DIY.Castle.Web.Models;
using DIY.Castle.Web.Services.ProductsService;
using DIY.Castle.Web.Services.SubcategoriesService;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;

namespace DIY.Castle.Web.Controllers
{
    public class CatalogController : BaseController
    {
        private readonly IProductsService productsService;

        public CatalogController(IProductsService productsService)
        {
            this.productsService = productsService;
        }

        public IActionResult Index(string filter = null, int page = 1, string searchQuery = "", string subCategory = "")
        {
            if (subCategory != null &&
                !string.IsNullOrEmpty(subCategory))
            {
                var prodModels = this.productsService
             .GetProductsBySubcategory(subCategory)
             .OrderByDescending(x => x.CreatedOn)
             .Select(x => this.productsService.GetProductModel(x))
             .ToList();

                var vm = PaginationList<ProductModel>.Create(prodModels, page, 12);
                return View(vm);
            }

            // Prevents from getting an error when clicking the search button with empty input ( ?searchQuery= )
            if (searchQuery is null)
            {
                searchQuery = string.Empty;
            }

            var isQueryNull = string.IsNullOrEmpty(searchQuery);
            var searchQueryLower = !isQueryNull ? searchQuery.ToLower() : searchQuery;

            Func<Product, bool> filterByStartsWith = (x) => !isQueryNull ?
            x.Name.ToLower().StartsWith(searchQueryLower) : true;

            Func<Product, bool> filterByStartsWithAndContains = (x) => !isQueryNull ?
            x.Name.ToLower().StartsWith(searchQueryLower) ||
            x.Name.ToLower().Contains(searchQueryLower) ||
            x.Subcategory.Name.ToLower().Contains(searchQueryLower) : true;

            var productModels = this.productsService
                .GetProductsByType(filter)
                .Where(searchQuery.Length < 5 ? filterByStartsWith : filterByStartsWithAndContains)
                .OrderByDescending(x => x.CreatedOn)
                //.Select(x => this.productsService.GetProductModel(x))
                .Select(x => this.productsService.GetProductModel(x))
                .ToList();

            var viewModel = PaginationList<ProductModel>.Create(productModels, page, 12);
            return View(viewModel);
        }

        //public IActionResult FilteredBySubcategory(string subcategory, int page = 1)
        //{
        //    var productModels = this.productsService
        //       .GetProductsBySubcategory(subcategory)
        //       .Select(x => this.productsService.GetProductModel(x))
        //       .OrderByDescending(x => x.CreatedOn)
        //       .ToList();

        //    var viewModel = PaginationList<ProductModel>.Create(productModels, page, 12);
        //    return View("/Views/Catalog/Index.cshtml", viewModel);
        //}
    }
}

DIY.Castle/DIY.Castle.Web/Controllers/ProductDetailsController.cs
using AutoMapper;
using DIY.Castle.Web.Models;
using DIY.Castle.Web.Models.ViewModels;
using DIY.Castle.Web.Services.ProductsService;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace DIY.Castle.Web.Controllers
{
    public class ProductDetailsController : BaseController
    {
        private readonly IProductsService productsService;
        private readonly IMapper mapper;

        public ProductDetailsController(IProductsService productsService, IMapper mapper)
        {
            this.productsService = productsService;
            this.mapper = mapper;
        }

        [Route("Product/{id}")]
        public IActionResult Product(int id)
        {
            var product = this.productsService.GetProductById(id);
            var vm = productsService.GetProductModel(product);

            return View(vm);
        }
    }
}

DIY.Castle/DIY.Castle.Web/Views/ProductDetails/Product.cshtml
@using GlobalConstants
@model ProductModel

<link href="/css/product-details.css" rel="stylesheet" />

<!--Section: Block Content-->
<body>
    <section class="mb-5">
        <div class="row">
            <div class="col-md-6">
                <div class="slideshow-container">
                    @foreach (var image in Model.ImagesSourcePaths)
                    {
                        <div class="mySlides faded">
                            @*<div class="numbertext">@(Model.ImagesSourcePaths.IndexOf(image)+1)/@Model.ImagesSourcePaths.Count</div>*@
                            <img src="@image" style=" object-fit: contain; height: 100%; width: 100%;">
                        </div>
                    }

                    <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
                    <a class="next" onclick="plusSlides(1)">&#10095;</a>

                </div>

                <div style="text-align:center">
                    @foreach (var dot in Model.ImagesSourcePaths)
                    {
                        <span class="dot" onclick="currentSlide(@(Model.ImagesSourcePaths.IndexOf(dot)+1))"></span>
                    }
                </div>
            </div>

            <div class="col-md-6 details-area">

                @if (User.IsInRole(UserRoles.ADMIN_ROLE_NAME))
                {
                    <div style="padding-bottom:30px;">
                        <a class="btn btn-warning control-buttons" asp-action="Edit" asp-controller="Products" asp-area="Administration" asp-route-productId="@Model.Id">Промени</a>

                        <button type="button" class="btn btn-danger control-buttons" data-toggle="modal" data-target="#deleteModal">
                            Изтрий
                        </button>
                        <partial name="~/Areas/Administration/Views/_ConfirmModal.cshtml" />

                        <button type="button" class="btn btn-info control-buttons" data-toggle="modal" data-target="#variationsModal">
                            Размери
                        </button>
                        <partial name="~/Areas/Administration/Views/Products/Variations.cshtml" />
                    </div>

                }
                <h5 class="heading">@Model.Name</h5>
                <a class="product-details-type text-muted text-uppercase small" asp-controller="Catalog" asp-action="Index" asp-route-filter="@Model.ProductType">
                    @Model.ProductType
                </a>
                <br />
                <a class="product-details-type text-muted text-uppercase small" asp-controller="Catalog" asp-action="Index" asp-route-subcategory="@Model.Subcategory">
                    @Model.Subcategory
                </a>
                <div class="product-description">
                    @Html.Raw(Model.Description)
                </div>


                <hr>
                <div style="display:flex; justify-content: space-between;">
                    <div class="counter btn">
                        <span class="down" onClick='decreaseCount(event, this)'>-</span>
                        <input id="product-quantity" type="text" value="1">
                        <span class="up" onClick='increaseCount(event, this)'>+</span>
                    </div>
                    <p style="text-align:right; right:0;"><strong class="product-details-price" id="sku-price">@Model.Price лв.</strong></p>
                </div>


                <div>
                    <select class="product-details-select" onchange="updatePriceOnVariationSelect()" @(Model.ProductVariations.Count == 1 ? "hidden" : "") id="selected-sku">
                        @for (int i = 0; i < Model.ProductVariations.Count; i++)
                        {
                            var sku = Model.ProductVariations[i];
                            var name = Model.ProductVariations.Count == 1 ? Model.Name : $"{Model.Name} - {sku.VariationName}";
                            var valueString = $"{ sku.Id}/{name}/{ sku.Price}";

                            if (i == 0)
                            {
                                <option selected id="sku-@sku.Id" value="@valueString">@sku.VariationName</option>
                            }
                            else
                            {
                                <option id="sku-@sku.Id" value="@valueString">@sku.VariationName</option>
                            }
                        }
                    </select>
                </div>



                <div style="padding-top:8px;" id="button-holder">
                    <a style="font-size: 25px; font-family: Guerrilla;" href="" data-ajax="true" data-ajax-success="AddToBasket(1)" class="btn button-product-details"><span style="color: #ab793d;">Добави в количката</span></a>
                </div>



            </div>
        </div>

    </section>


</body>
<!--Section: Block Content-->
<script>
    function updatePriceOnVariationSelect() {
        var el = document.getElementById('sku-price');
        var optionValueArgs = document.getElementById('selected-sku').value.split('/');
        var skuPrice = optionValueArgs[2];

        el.innerHTML = `${skuPrice} лв.`;
    }

</script>
<script src="/js/product-details.js" rel="stylesheet"></script>