DIY.Castle/DIY.Castle.Web/Controllers/CatalogController.cs
using DIY.Castle.Common;
using DIY.Castle.Data.Models;
using DIY.Castle.Web.Models;
using DIY.Castle.Web.Services.ProductsService;
using DIY.Castle.Web.Services.SubcategoriesService;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;

namespace DIY.Castle.Web.Controllers
{
    public class CatalogController : BaseController
    {
        private readonly IProductsService productsService;

        public CatalogController(IProductsService productsService)
        {
            this.productsService = productsService;
        }

        public IActionResult Index(string filter = null, int page = 1, string searchQuery = "", string subCategory = "")
        {
            if (subCategory != null &&
                !string.IsNullOrEmpty(subCategory))
            {
                var prodModels = this.productsService
             .GetProductsBySubcategory(subCategory)
             .OrderByDescending(x => x.CreatedOn)
             .Select(x => this.productsService.GetProductModel(x))
             .ToList();

                var vm = PaginationList<ProductModel>.Create(prodModels, page, 12);
                return View(vm);
            }

            // Prevents from getting an error when clicking the search button with empty input ( ?searchQuery= )
            if (searchQuery is null)
            {
                searchQuery = string.Empty;
            }

            var isQueryNull = string.IsNullOrEmpty(searchQuery);
            var searchQueryLower = !isQueryNull ? searchQuery.ToLower() : searchQuery;

            Func<Product, bool> filterByStartsWith = (x) => !isQueryNull ?
            x.Name.ToLower().StartsWith(searchQueryLower) : true;

            Func<Product, bool> filterByStartsWithAndContains = (x) => !isQueryNull ?
            x.Name.ToLower().StartsWith(searchQueryLower) ||
            x.Name.ToLower().Contains(searchQueryLower) ||
            x.Subcategory.Name.ToLower().Contains(searchQueryLower) : true;

            var productModels = this.productsService
                .GetProductsByType(filter)
                .Where(searchQuery.Length < 5 ? filterByStartsWith : filterByStartsWithAndContains)
                .OrderByDescending(x => x.CreatedOn)
                //.Select(x => this.productsService.GetProductModel(x))
                .Select(x => this.productsService.GetProductModel(x))
                .ToList();

            var viewModel = PaginationList<ProductModel>.Create(productModels, page, 12);
            return View(viewModel);
        }

        //public IActionResult FilteredBySubcategory(string subcategory, int page = 1)
        //{
        //    var productModels = this.productsService
        //       .GetProductsBySubcategory(subcategory)
        //       .Select(x => this.productsService.GetProductModel(x))
        //       .OrderByDescending(x => x.CreatedOn)
        //       .ToList();

        //    var viewModel = PaginationList<ProductModel>.Create(productModels, page, 12);
        //    return View("/Views/Catalog/Index.cshtml", viewModel);
        //}
    }
}

DIY.Castle/DIY.Castle.Web/Controllers/ProductDetailsController.cs
using AutoMapper;
using DIY.Castle.Web.Models;
using DIY.Castle.Web.Models.ViewModels;
using DIY.Castle.Web.Services.ProductsService;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace DIY.Castle.Web.Controllers
{
    public class ProductDetailsController : BaseController
    {
        private readonly IProductsService productsService;
        private readonly IMapper mapper;

        public ProductDetailsController(IProductsService productsService, IMapper mapper)
        {
            this.productsService = productsService;
            this.mapper = mapper;
        }

        [Route("Product/{id}")]
        public IActionResult Product(int id)
        {
            var product = this.productsService.GetProductById(id);
            var vm = productsService.GetProductModel(product);

            return View(vm);
        }
    }
}

DIY.Castle/DIY.Castle.Web/Views/Catalog/Index.cshtml
@using DIY.Castle.Web.Models
@using DIY.Castle.Common
@model PaginationList<ProductModel>

@{
    var currenSearchQueryTry = Context.Request.Query.TryGetValue("searchQuery", out Microsoft.Extensions.Primitives.StringValues currenSearchQuery);
}

<!DOCTYPE html>
<html>
<head>
    <link href="/css/catalog-page.css" rel="stylesheet" />
</head>

<body>
    <div class="wrap">
        <form>
            <div class="search">
                <input autocomplete="off" name="searchQuery" value="@currenSearchQuery" type="text" class="searchTerm" placeholder="Търсене на продукт...">
                <button type="submit" class="searchButton">
                    <i class="fa fa-search"></i>
                </button>
            </div>
        </form>
    </div>
    <div class="@*container*@">
        @if (Model.Any())
        {
            <div class="row">
                @foreach (ProductModel product in Model)
                {
                <div class="col-xs-12 col-md-6 col-lg-3">
                    <!-- First product box start here-->
                    <div class="prod-info-main prod-wrap clearfix">
                        <div class="row">
                            <div class="col-12">
                                <div class="product-image">
                                    <img style="object-fit: contain;" src="@product.ImagesSourcePaths[0]" class="img-responsive rotprod">
                                    @if (product.IsNewProduct)
                                    {
                                        <span class="tag2 hot">
                                            НОВО
                                        </span>
                                    }
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="product-deatil">
                                    <h5 class="name">
                                        <a style="color: #ab793d; font-family: 'Phenomena-ExtraBold'; font-size:24px;" asp-controller="ProductDetails" asp-action="Product" asp-route-id="@product.Id">
                                            @product.Name
                                        </a>
                                        @*<a class="product-type">
                                                <span style="padding-top:7px;">@product.ProductType</span>
                                            </a>*@
                                        <a class="product-type" asp-controller="Catalog" asp-action="Index" asp-route-filter="@product.ProductType">
                                            <span style="padding-top:7px;">@product.ProductType</span>
                                        </a>
                                        <a class="product-type" asp-controller="Catalog" asp-action="Index" asp-route-subcategory="@product.Subcategory">
                                            <span>@product.Subcategory</span>
                                        </a>
                                    </h5>
                                    <span class="tag1"></span>
                                </div>
                                <div class="product-info smart-form">
                                    <div style="justify-content: space-between" class="row">
                                        @if (product.ProductVariations.Count == 1)
                                        {
                                            var firstSku = product.ProductVariations.FirstOrDefault();
                                            <a href="" data-ajax="true" data-ajax-success="AddToBasket('1', '@firstSku.Id', '@product.Name', '@firstSku.Price')" class="btn btn-info"><span>Добави</span></a>
                                        }

                                        <a asp-controller="ProductDetails" asp-action="Product" asp-route-id="@product.Id" class="btn btn-info"><span>Детайли</span></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- end product -->
                </div>
                }
            </div>
        }
        else
        {
            <partial name="../Catalog/_NoProductsFound.cshtml" />
        }



    </div>

    @*Pagination*@

    <partial name="../Shared/_Pagination.cshtml" model=@Model />

    @*Pagination*@

</body>
</html>

DIY.Castle/DIY.Castle.Web/Views/Catalog/_NoProductsFound.cshtml
<div style="place-content: center" class="row">
    <img class="no-products-found" style="max-width:45%" src="~/images/error/product-does-not-exist.png" />
</div>

<script>
    const element = document.querySelector('.no-products-found');
    element.classList.add('animate__animated', 'animate__rubberBand');
</script>