DIY.Castle/DIY.Castle.Web/Areas/Administration/Controllers/ProductVariationsController.cs
using AutoMapper;
using DIY.Castle.Data.Models;
using DIY.Castle.Web.Areas.Administration.Models;
using DIY.Castle.Web.Areas.Administration.Models.Variations;
using DIY.Castle.Web.Services.CategoriesService;
using DIY.Castle.Web.Services.ProductsService;
using DIY.Castle.Web.Services.ProductVariationsService;
using DIY.Castle.Web.Services.UploadFileService;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DIY.Castle.Web.Areas.Administration.Controllers
{
    public class ProductVariationsController : AdministrationController
    {
        private readonly IProductsService _productsService;
        private readonly IProductVariationsService productVariationsService;

        public ProductVariationsController(IProductsService productsService, IProductVariationsService productVariationsService)
        {
            this._productsService = productsService;
            this.productVariationsService = productVariationsService;
        }

        [HttpGet]
        public IActionResult Add(int productId)
        {
            var product = this._productsService.GetProductById(productId);

            var model = new CreateVariationProductRequestModel();
            model.ProductId = productId;

            return this.View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Add(CreateVariationProductRequestModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            await this.productVariationsService.CreateVariation(model);

            return RedirectToAction("Product", "ProductDetails", new { area = "", id = model.ProductId });
        }

        [HttpGet]
        public IActionResult Edit(int variationId)
        {
            var variation = this._productsService.GetVariationById(variationId);

            var model = new EditVariationProductRequestModel();
            model.VariationId = variationId;
            model.ProductId = variation.ProductId;
            model.Name = variation.VariationName;
            model.Price = variation.Price;

            return this.View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditVariationProductRequestModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            var variation = await this.productVariationsService.EditVariation(model);

            return RedirectToAction("Product", "ProductDetails", new { area = "", id = variation.ProductId });
        }

        public async Task<IActionResult> Delete(int variationId)
        {
            var variation = this._productsService.GetVariationById(variationId);

            await this.productVariationsService.DeleteVariation(variation);

            return RedirectToAction("Product", "ProductDetails", new { area = "", id = variation.ProductId });
        }
    }
}

DIY.Castle/DIY.Castle.Web/Areas/Administration/Views/ProductVariations/Add.cshtml
@using DIY.Castle.Web.Areas.Administration.Models.Variations
@model CreateVariationProductRequestModel

<style>
    .validation_summary ul {
        list-style-type: none;
        font-family: Verdana;
    }
</style>

<div class="col-sm-5 mx-auto py-4">
    <div class="card">
        <div style="background-color:green" class="card-header text-uppercase text-white">
            <h4>Добавяне на подпродукт</h4>
        </div>
        <div class="card-body">
            <form enctype="multipart/form-data" asp-area="Administration" asp-controller="ProductVariations" asp-action="Add" method="post">
                <input hidden value="@Model.ProductId" asp-for="@Model.ProductId" />
                <div class="validation_summary text-danger" style="text-align:left;list-style:none;" asp-validation-summary="All"></div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label asp-for="@Model.Name" class="control-label">Име</label>
                            <input asp-for="@Model.Name" class="form-control" />
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label asp-for="@Model.Price" class="control-label">Цена на подпродукт</label>
                            <input min="0.00" max="10000.00" asp-for="@Model.Price" class="form-control" />
                        </div>
                    </div>
                </div>
                <div style="display:flex; justify-content:space-between;" class="form-group">
                    <a style="color: white" type="button" asp-area="" asp-controller="ProductDetails" asp-action="Product" asp-route-id="@Model.ProductId" class="btn btn-lg btn-danger rounded-0 text-uppercase">откажи</a>
                    <input type="submit" value="създай" class="btn btn-lg btn-primary rounded-0 text-uppercase" />
                </div>
            </form>
        </div>
    </div>
</div>

DIY.Castle/DIY.Castle.Web/Areas/Administration/Views/ProductVariations/Edit.cshtml
@using DIY.Castle.Web.Areas.Administration.Models.Variations
@model EditVariationProductRequestModel

<style>
    .validation_summary ul {
        list-style-type: none;
        font-family: Verdana;
    }
</style>

<div class="col-sm-5 mx-auto py-4">
    <div class="card">
        <div style="background-color:green" class="card-header text-uppercase text-white">
            <h4>Промяна на подпродукт</h4>
        </div>
        <div class="card-body">
            <form asp-area="Administration" asp-controller="ProductVariations" asp-action="Edit" method="post">
                <input hidden value="@Model.VariationId" asp-for="@Model.VariationId" />
                <input hidden value="@Model.ProductId" asp-for="@Model.ProductId" />
                <div class="validation_summary text-danger" style="text-align:left;list-style:none;" asp-validation-summary="All"></div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label asp-for="@Model.Name" class="control-label">Име</label>
                            <input asp-for="@Model.Name" class="form-control" />
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label asp-for="@Model.Price" class="control-label">Цена на продпродукт</label>
                            <input min="0.00" max="10000.00"  asp-for="@Model.Price" class="form-control" />
                        </div>
                    </div>
                </div>
                <div style="display:flex; justify-content:space-between;" class="form-group">
                    <a style="color: white" type="button" asp-area="" asp-controller="ProductDetails" asp-action="Product" asp-route-id="@Model.ProductId" class="btn btn-lg btn-danger rounded-0 text-uppercase">откажи</a>
                    <input type="submit" value="промени" class="btn btn-lg btn-primary rounded-0 text-uppercase" />
                </div>
            </form>
        </div>
    </div>
</div>