DIY.Castle/DIY.Castle.Web/Models/ViewModels/CartViewModel.cs
using System.Collections.Generic;

namespace DIY.Castle.Web.Models.ViewModels
{
    public class CartViewModel
    {
        public List<ProductCartModel> Cart { get; set; }

        public decimal TotalPrice { get; set; }
    }

    public class ProductCartModel
    {
        public int Quantity { get; set; }

        public VariationProductModel ProductVariation { get; set; }
    }
}

DIY.Castle/DIY.Castle.Web/Controllers/CartController.cs
using AutoMapper;
using DIY.Castle.Web.Helpers;
using DIY.Castle.Web.Models;
using DIY.Castle.Web.Models.Response;
using DIY.Castle.Web.Models.ViewModels;
using DIY.Castle.Web.Services.ProductsService;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DIY.Castle.Web.Controllers
{
    [Route("cart")]
    public class CartController : BaseController
    {
        private readonly IProductsService _productsService;

        public CartController(
            IProductsService productsService)
        {
            this._productsService = productsService;
        }

        [Route("GetTotalPrice")]
        public IActionResult GetTotalPrice()
        {
            var cart = SessionHelper.GetObjectFromJson<List<ProductCartModel>>(HttpContext.Session, "cart");
            var totalPrice = cart == null
                ? Math.Round(0.00M, 2)
                : Math.Round(cart.Sum(p => p.ProductVariation.Price * p.Quantity), 2);

            string response = totalPrice.ToString("0.00");
            return this.Ok(response);
        }

        [Route("GetSubTotalPrice/{id}")]
        public IActionResult GetSubTotalPrice(int id)
        {
            var cart = SessionHelper.GetObjectFromJson<List<ProductCartModel>>(HttpContext.Session, "cart");

            int index = GetItemIndexInCart(id);
            var cartProduct = index != -1 ? cart[index] : null;

            var subTotalPrice = cartProduct == null ? 0.00M :
               Math.Round((cartProduct.Quantity * cartProduct.ProductVariation.Price), 2);

            string response = subTotalPrice.ToString("0.00");
            return this.Ok(response);
        }

        [Route("AddToBasket/{id}/{quantity}")]
        // pass variation id instead of product
        public IActionResult AddToBasket(int id, int quantity)
        {
            try
            {
                var variation = this._productsService.GetVariationById(id);
                bool itemAlreadyExists = false;
                decimal totalPrice = 0.00M;
                int updatedQuantity = 0;
                int updatedTotalQuantity = 0;
                var variationProductModel = this._productsService.GetProductVariationModel(variation);

                string imageSource = variationProductModel.ImagesSourcePaths.Any() ? variationProductModel.ImagesSourcePaths[0] : string.Empty;

                if (SessionHelper.GetObjectFromJson<List<ProductCartModel>>(HttpContext.Session, "cart") == null)
                {
                    var cart = new List<ProductCartModel>();

                    cart.Add(new ProductCartModel
                    {
                        ProductVariation = variationProductModel,
                        Quantity = quantity
                    });

                    SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);

                    totalPrice = variation.Price;
                    updatedQuantity = quantity;
                    updatedTotalQuantity = 1;
                }
                else
                {
                    List<ProductCartModel> cart = SessionHelper.GetObjectFromJson<List<ProductCartModel>>(HttpContext.Session, "cart");

                    int index = GetItemIndexInCart(id);

                    // If the item already exists in the cart
                    if (index != -1)
                    {
                        cart[index].Quantity += quantity;
                        itemAlreadyExists = true;

                        updatedQuantity = cart[index].Quantity;
                    }
                    // If it doesn't
                    else
                    {
                        cart.Add(new ProductCartModel
                        {
                            ProductVariation = variationProductModel,
                            Quantity = quantity
                        });

                        updatedQuantity = quantity;
                    }

                    SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);

                    totalPrice = cart == null
                        ? Math.Round(0.00M, 2)
                        : Math.Round(cart.Sum(p => p.ProductVariation.Price * p.Quantity), 2);
                    updatedTotalQuantity = cart.Count();
                }

                var response = new CartUpdateResponseModel()
                {
                    ItemAlreadyExists = itemAlreadyExists,
                    UpdatedPrice = totalPrice.ToString("0.00"),
                    UpdatedQuantity = updatedQuantity,
                    UpdatedTotalQuantity = updatedTotalQuantity,
                    ImageSource = imageSource,
                };

                return this.Ok(Json(response));
            }
            catch (Exception msg)
            {
                return this.BadRequest();
            }

        }

        [Route("Remove/{id}")]
        public IActionResult Remove(int id)
        {
            List<ProductCartModel> cart = SessionHelper.GetObjectFromJson<List<ProductCartModel>>(HttpContext.Session, "cart");
            try
            {
                int index = GetItemIndexInCart(id);
                cart.RemoveAt(index);
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            }
            catch (Exception)
            {
                return NotFound();
            }
            return NoContent();
        }

        [Route("IncreaseQuantity/{id}")]
        public IActionResult IncreaseQuantity(int id)
        {
            List<ProductCartModel> cart = SessionHelper.GetObjectFromJson<List<ProductCartModel>>(HttpContext.Session, "cart");

            int index = GetItemIndexInCart(id);

            if (index != -1)
            {
                cart[index].Quantity++;
            }

            SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);

            return NoContent();
        }

        [Route("DecreaseQuantity/{id}")]
        public IActionResult DecreaseQuantity(int id)
        {
            List<ProductCartModel> cart = SessionHelper.GetObjectFromJson<List<ProductCartModel>>(HttpContext.Session, "cart");

            int index = GetItemIndexInCart(id);

            if (index != -1 &&
                cart[index].Quantity - 1 > 0)
            {
                cart[index].Quantity--;
            }

            SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);

            return NoContent();
        }

        private int GetItemIndexInCart(int id)
        {
            List<ProductCartModel> cart = SessionHelper.GetObjectFromJson<List<ProductCartModel>>(HttpContext.Session, "cart");

            for (int i = 0; i < cart.Count; i++)
            {
                if (cart[i].ProductVariation.Id.Equals(id))
                {
                    return i;
                }
            }
            return -1;
        }

    }
}

DIY.Castle/DIY.Castle.Web/Controllers/CheckoutPageController.cs
using DIY.Castle.Data.Models;
using DIY.Castle.Web.Helpers;
using DIY.Castle.Web.Models.Emails;
using DIY.Castle.Web.Models.InputModels;
using DIY.Castle.Web.Models.ViewModels;
using DIY.Castle.Web.Services.EmailSender;
using DIY.Castle.Web.Services.ProductsService;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;

namespace DIY.Castle.Web.Controllers
{
    public class CheckoutPageController : BaseController
    {
        private readonly IEmailSender emailSender;

        public CheckoutPageController(
            IEmailSender emailSender)
        {
            this.emailSender = emailSender;
        }

        public IActionResult Index()
        {
            return this.View();
        }

        [HttpPost]
        public async Task<IActionResult> Checkout(CheckoutFormModel model)
        {
            if (model.CourrierOption == GlobalConstants.DeliveryOptions.Econt)
            {
                if (model.DeliveryOption == GlobalConstants.DeliveryOptions.ToOffice &&
                    string.IsNullOrEmpty(model.EcontOffice))
                {
                    ModelState.AddModelError("EcontOffice", "Нямате избран офис");
                }
                else if (model.DeliveryOption == GlobalConstants.DeliveryOptions.ToAddress &&
                        string.IsNullOrEmpty(model.Address))
                {
                    ModelState.AddModelError("Address", "Нямате избран адрес");
                }
                else
                {
                    if (string.IsNullOrEmpty(model.DeliveryOption))
                    {
                        ModelState.AddModelError("DeliveryOption", "Трябва да изберете адрес или офис");
                    }
                }
            }
            else
            {
                if (string.IsNullOrEmpty(model.Address))
                {
                    ModelState.AddModelError("Address", "Нямате избран адрес");
                }
            }
            if (!ModelState.IsValid)
            {
                return this.View(nameof(Index), model);
            }

            var cart = SessionHelper.GetObjectFromJson<List<ProductCartModel>>(HttpContext.Session, "cart");
            var totalPrice = cart == null
                           ? Math.Round(0.00M, 2)
                           : Math.Round(cart.Sum(p => p.ProductVariation.Price * p.Quantity), 2);

            var cartModel = new CartViewModel()
            {
                Cart = cart,
                TotalPrice = totalPrice,
            };

            var checkoutModel = new CheckoutModel()
            {
                CartModel = cartModel,
                UserFormModel = model,
            };

            if (model.CourrierOption == GlobalConstants.DeliveryOptions.Econt)
            {
                if (model.DeliveryOption == GlobalConstants.DeliveryOptions.ToOffice)
                {
                    checkoutModel.UserFormModel.Address = model.EcontOffice;
                }
            }

            // Send Email To Customer Service
            var customerServiceViewHtml = await this.RenderViewAsync("~/Views/EmailTemplates/OrderTemplate.cshtml", checkoutModel, true);

            await this.emailSender.SendEmailAsync($"mail@abv.bg", "Akin-do Поръчка", $"akindo.customerservice@gmail.com", $"{model.FirstName} {model.LastName}", customerServiceViewHtml);

            // Send Email To Customer
            //await this.SendOrderSummaryEmailToUserAsync(checkoutModel);

            return this.RedirectToAction(nameof(OrderCompleted));
        }

        public IActionResult OrderCompleted()
        {
            return this.View();
        }

        private async Task<IActionResult> SendOrderSummaryEmailToUserAsync(CheckoutModel model)
        {
            var viewHtml = await this.RenderViewAsync("~/Views/EmailTemplates/OrderSummaryTemplate.cshtml", model, true);

            try
            {
                await this.emailSender.SendEmailAsync($"mail@abv.bg", $"Akin-do", $"{model.UserFormModel.CustomerEmailAddress}", $"Akin-do Поръчка - {model.CartModel.TotalPrice} лв.", viewHtml);

                return Ok();
            }
            catch (System.Exception msg)
            {
                // TODO... 

                return BadRequest();
            }


        }
    }
}

DIY.Castle/DIY.Castle.Web/Views/Cart/_cart.cshtml
@using DIY.Castle.Web.Helpers;
@using DIY.Castle.Web.Models.ViewModels;

@{
    var cart = SessionHelper.GetObjectFromJson<List<ProductCartModel>>(Context.Session, "cart");

    var totalPrice = cart == null
        ? Math.Round(0.00M, 2)
        : Math.Round(cart.Sum(p => p.ProductVariation.Price * p.Quantity), 2);

    string priceString = totalPrice.ToString("0.00");
}

<style>
    .tag2 {
        position: absolute;
        /* top: 20%; */
        /* right: 43%; */
        width: 25px;
        /* height: 36px; */
        border-radius: 50%;
        /* padding: 10px 0; */
        padding-left: 2px;
        color: #fff;
        font-size: 15px;
        text-align: center;
    }

    .hot {
        background-color: #a90329;
    }

    .cart-product-img{
        width:50px;
        height:50px;
        border-radius:25px;
    }

    .cd-cart-heading {
        text-align: center;
        padding-bottom: 20px;
        font-family:Yarin;
    }
</style>


<!doctype html>
<html lang="en" class="no-js">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    @*<link rel="stylesheet" href="/side-shopping-cart/css/reset.css"> <!-- CSS reset -->*@
    <link rel="stylesheet" href="/side-shopping-cart/css/style.css"> <!-- Gem style -->
    @*<script src="/side-shopping-cart/js/modernizr.js"></script> <!-- Modernizr -->*@
</head>
<body class="foo">
    <div>
        <div id="cd-cart-trigger">
            <a class="cd-img-replace"></a>
            <span id="cart-items-count" class="tag2 hot" @(cart?.Count() <= 0 ? "hidden" : "")>@cart?.Count()</span>
        </div>
    </div>

    <div id="cd-shadow-layer"></div>

    <div style="font-family: Verdana; font-size: 16px; background-color: #FAF8F0;" id="cd-cart">
        <h3 class="cd-cart-heading">Количка с продукти</h3>
        <ul id="cart-items" class="cd-cart-items">
            @if (cart != null)
            {
                foreach (var item in cart)
                {
                    <li id="item-id-@item.ProductVariation.Id">
                        <img class="cart-product-img" src="@item.ProductVariation.ImagesSourcePaths[0]">
                        <span class="cd-qty">@(item.Quantity)X </span>
                        <span>@item.ProductVariation.Name</span>
                        <div class="cd-price">@item.ProductVariation.Price лв.</div>
                        <a asp-controller="Cart" asp-action="Remove" asp-route-id="@item.ProductVariation.Id" data-ajax="true" data-ajax-success="deleteItem(this, '@item.ProductVariation.Name')"
                           id="remove-item-@item.ProductVariation.Id" class="cd-item-remove cd-img-replace">
                            Премахни
                        </a>
                    </li>
                }
            }
        </ul>

        <div id="total-price" class="cd-cart-total">
            <p>Крайна цена <span>@priceString лв.</span></p>
        </div>

        <a asp-action="Index" asp-controller="CheckoutPage" class="checkout-btn">Завърши поръчката</a>
    </div>
</body>
</html>